/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.organivent.view;

import ec.edu.espe.organivent.controller.BillController;
import ec.edu.espe.organivent.model.Bill;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jefferson Yepez, DCCO - ESPE, BitCoderz
 */
public class FrmCalculateTotalCostEvent extends javax.swing.JFrame {

    /**
     * Creates new form FrmTotalAmountEvent
     */
    public FrmCalculateTotalCostEvent() {
        initComponents();
        loadBill();
    }
       
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtId = new javax.swing.JLabel();
        cmbIdBill = new javax.swing.JComboBox<>();
        txtArtistCost1 = new javax.swing.JLabel();
        txtVenueCost = new javax.swing.JLabel();
        txtVenueCost1 = new javax.swing.JLabel();
        txtStaffCost1 = new javax.swing.JLabel();
        txtEquipmentCost1 = new javax.swing.JLabel();
        txtGeneralExpensesCost1 = new javax.swing.JLabel();
        txtPenaltyFeesCost1 = new javax.swing.JLabel();
        txtArtistCost = new javax.swing.JLabel();
        txtStaffCost = new javax.swing.JLabel();
        txtEquipmentCost = new javax.swing.JLabel();
        txtPenaltyFeesCost = new javax.swing.JLabel();
        txtGeneralExpensesCost = new javax.swing.JLabel();
        txtTotalAmount1 = new javax.swing.JLabel();
        btnBackMenu = new javax.swing.JPanel();
        txtDeleteBillbtn = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(32, 108, 141));
        txtTitle.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtTitle.text")); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(116, 178, 237));

        txtId.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtId.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtId.text")); // NOI18N

        cmbIdBill.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        cmbIdBill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIdBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbIdBillMouseClicked(evt);
            }
        });

        txtArtistCost1.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtArtistCost1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtArtistCost1.text")); // NOI18N

        txtVenueCost.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtVenueCost.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtVenueCost.text")); // NOI18N

        txtVenueCost1.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtVenueCost1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtVenueCost1.text")); // NOI18N

        txtStaffCost1.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtStaffCost1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtStaffCost1.text")); // NOI18N

        txtEquipmentCost1.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtEquipmentCost1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtEquipmentCost1.text")); // NOI18N

        txtGeneralExpensesCost1.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtGeneralExpensesCost1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtGeneralExpensesCost1.text")); // NOI18N

        txtPenaltyFeesCost1.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtPenaltyFeesCost1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtPenaltyFeesCost1.text")); // NOI18N

        txtArtistCost.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtArtistCost.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtArtistCost.text")); // NOI18N

        txtStaffCost.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtStaffCost.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtStaffCost.text")); // NOI18N

        txtEquipmentCost.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtEquipmentCost.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtEquipmentCost.text")); // NOI18N

        txtPenaltyFeesCost.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtPenaltyFeesCost.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtPenaltyFeesCost.text")); // NOI18N

        txtGeneralExpensesCost.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        txtGeneralExpensesCost.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtGeneralExpensesCost.text")); // NOI18N

        txtTotalAmount1.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        txtTotalAmount1.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtTotalAmount1.text")); // NOI18N

        btnBackMenu.setBackground(new java.awt.Color(63, 115, 193));
        btnBackMenu.setMaximumSize(new java.awt.Dimension(142, 47));
        btnBackMenu.setMinimumSize(new java.awt.Dimension(142, 47));
        btnBackMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMenuMouseClicked(evt);
            }
        });

        txtDeleteBillbtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtDeleteBillbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtDeleteBillbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDeleteBillbtn.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtDeleteBillbtn.text")); // NOI18N
        txtDeleteBillbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDeleteBillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDeleteBillbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDeleteBillbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackMenuLayout = new javax.swing.GroupLayout(btnBackMenu);
        btnBackMenu.setLayout(btnBackMenuLayout);
        btnBackMenuLayout.setHorizontalGroup(
            btnBackMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDeleteBillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, Short.MAX_VALUE)
        );
        btnBackMenuLayout.setVerticalGroup(
            btnBackMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackMenuLayout.createSequentialGroup()
                .addComponent(txtDeleteBillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtTotalAmount.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        txtTotalAmount.setText(org.openide.util.NbBundle.getMessage(FrmCalculateTotalCostEvent.class, "FrmCalculateTotalCostEvent.txtTotalAmount.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(txtId)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVenueCost1)
                                    .addComponent(txtArtistCost1)
                                    .addComponent(txtStaffCost1)
                                    .addComponent(txtEquipmentCost1)
                                    .addComponent(txtGeneralExpensesCost1)
                                    .addComponent(txtPenaltyFeesCost1)
                                    .addComponent(txtTotalAmount1))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbIdBill, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVenueCost, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArtistCost, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffCost, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEquipmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPenaltyFeesCost, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneralExpensesCost, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitle)
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbIdBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArtistCost1)
                    .addComponent(txtArtistCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVenueCost1)
                    .addComponent(txtVenueCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffCost1)
                    .addComponent(txtStaffCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEquipmentCost1)
                    .addComponent(txtEquipmentCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneralExpensesCost1)
                    .addComponent(txtGeneralExpensesCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenaltyFeesCost1)
                    .addComponent(txtPenaltyFeesCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAmount1)
                    .addComponent(txtTotalAmount))
                .addGap(31, 31, 31)
                .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIdBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbIdBillMouseClicked
        Bill bill = getSelectedBill();
        txtArtistCost.setText(String.valueOf(bill.getArtistCost()));
        txtVenueCost.setText(String.valueOf(bill.getVenueCost()));
        txtStaffCost.setText(String.valueOf(bill.getStaffCost()));
        txtEquipmentCost.setText(String.valueOf(bill.getEquipmentCost()));
        txtGeneralExpensesCost.setText(String.valueOf(bill.getGeneralExpensesCost()));
        txtPenaltyFeesCost.setText(String.valueOf(bill.getPenaltyFeesCost()));      
        txtTotalAmount.setText(String.valueOf(bill.getTotalAmount()));
        
    }//GEN-LAST:event_cmbIdBillMouseClicked

    private void txtDeleteBillbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteBillbtnMouseEntered

    }//GEN-LAST:event_txtDeleteBillbtnMouseEntered

    private void txtDeleteBillbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteBillbtnMouseExited

    }//GEN-LAST:event_txtDeleteBillbtnMouseExited

    private void btnBackMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMenuMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnBackMenuMouseClicked

    private void loadBill() {
        DefaultComboBoxModel<String> listModel = new DefaultComboBoxModel();
        BillController bll = new BillController();

        ArrayList<Bill> availableBills = bll.readTable();

        String display;

        for (Bill currentBill : availableBills) {
            display = String.valueOf(currentBill.getId());
            listModel.addElement(display);
        }

        cmbIdBill.setModel(listModel);
    }

    private Bill getSelectedBill() {
        Bill selectedBill;
        BillController bll = new BillController();
        int reladtedId;

        String indexContent = String.valueOf(cmbIdBill.getSelectedItem());

        reladtedId = Integer.parseInt(Character.toString(indexContent.charAt(0)));

        selectedBill = bll.findOne(reladtedId);

        
        return selectedBill;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalculateTotalCostEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalculateTotalCostEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalculateTotalCostEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalculateTotalCostEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalculateTotalCostEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBackMenu;
    private javax.swing.JComboBox<String> cmbIdBill;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtArtistCost;
    private javax.swing.JLabel txtArtistCost1;
    private javax.swing.JLabel txtDeleteBillbtn;
    private javax.swing.JLabel txtEquipmentCost;
    private javax.swing.JLabel txtEquipmentCost1;
    private javax.swing.JLabel txtGeneralExpensesCost;
    private javax.swing.JLabel txtGeneralExpensesCost1;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtPenaltyFeesCost;
    private javax.swing.JLabel txtPenaltyFeesCost1;
    private javax.swing.JLabel txtStaffCost;
    private javax.swing.JLabel txtStaffCost1;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTotalAmount;
    private javax.swing.JLabel txtTotalAmount1;
    private javax.swing.JLabel txtVenueCost;
    private javax.swing.JLabel txtVenueCost1;
    // End of variables declaration//GEN-END:variables
}
