/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.organivent.view;

import ec.edu.espe.organivent.controller.EventPlaceController;
import ec.edu.espe.organivent.model.EventPlace;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmReadEventPlace extends javax.swing.JFrame {

    /**
     * Creates new form FrmReadEventPlace
     */
    public FrmReadEventPlace() {
        initComponents();
        readEventPlace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReadEventPlace = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setText(org.openide.util.NbBundle.getMessage(FrmReadEventPlace.class, "FrmReadEventPlace.txtTitle.text")); // NOI18N
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 20, -1, -1));

        tblReadEventPlace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Direccion", "Costo", "Capacidad"
            }
        ));
        jScrollPane1.setViewportView(tblReadEventPlace);
        if (tblReadEventPlace.getColumnModel().getColumnCount() > 0) {
            tblReadEventPlace.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmReadEventPlace.class, "FrmReadEventPlace.tblReadEventPlace.columnModel.title0")); // NOI18N
            tblReadEventPlace.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmReadEventPlace.class, "FrmReadEventPlace.tblReadEventPlace.columnModel.title1")); // NOI18N
            tblReadEventPlace.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmReadEventPlace.class, "FrmReadEventPlace.tblReadEventPlace.columnModel.title2")); // NOI18N
            tblReadEventPlace.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmReadEventPlace.class, "FrmReadEventPlace.tblReadEventPlace.columnModel.title3")); // NOI18N
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReadEventPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReadEventPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReadEventPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReadEventPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReadEventPlace().setVisible(true);
            }
        });
    }
    
    private void readEventPlace() {
    EventPlaceController evplc = new EventPlaceController();
    ArrayList<EventPlace> eventPlaceList = evplc.read();

    DefaultTableModel model = (DefaultTableModel) tblReadEventPlace.getModel();
    model.setRowCount(0); // Clear existing rows

    for (EventPlace eventPlace : eventPlaceList) {
        Object[] rowData = {eventPlace.getName(), eventPlace.getAdress(), eventPlace.getRentCost(), eventPlace.getCapacity()};
        model.addRow(rowData);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReadEventPlace;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
