package ec.edu.espe.organivent.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Frederick
 */
public class FrmSpashcreen extends javax.swing.JFrame  {
    
    
    Timer timer = new Timer(1500,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            FrmLogIn frmLogIn = new FrmLogIn();
            frmLogIn.setVisible(true);
            endTimer();
        }
    
    });

    /**
     * Creates new form FrmSpashcreen
     */
    public FrmSpashcreen() {
        initComponents();
        timer.start();
        
    }
    
    public void endTimer(){
        timer.stop();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pnlRectangle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(FrmSpashcreen.class, "FrmSpashcreen.title")); // NOI18N
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(576, 323));

        background.setBackground(new java.awt.Color(245, 254, 255));
        background.setMaximumSize(new java.awt.Dimension(576, 323));
        background.setMinimumSize(new java.awt.Dimension(576, 323));
        background.setPreferredSize(new java.awt.Dimension(576, 323));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRectangle.setBackground(new java.awt.Color(235, 251, 251));
        pnlRectangle.setPreferredSize(new java.awt.Dimension(322, 69));

        jLabel1.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmSpashcreen.class, "FrmSpashcreen.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmSpashcreen.class, "FrmSpashcreen.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout pnlRectangleLayout = new javax.swing.GroupLayout(pnlRectangle);
        pnlRectangle.setLayout(pnlRectangleLayout);
        pnlRectangleLayout.setHorizontalGroup(
            pnlRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRectangleLayout.createSequentialGroup()
                .addGroup(pnlRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRectangleLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(pnlRectangleLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlRectangleLayout.setVerticalGroup(
            pnlRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRectangleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        background.add(pnlRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 223, -1, -1));

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/organivent_logo.png"))); // NOI18N
        logoImg.setText(org.openide.util.NbBundle.getMessage(FrmSpashcreen.class, "FrmSpashcreen.logoImg.text")); // NOI18N
        background.add(logoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 26, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSpashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSpashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSpashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSpashcreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSpashcreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoImg;
    private javax.swing.JPanel pnlRectangle;
    // End of variables declaration//GEN-END:variables

}
