package ec.edu.espe.organivent.view;

import com.raven.glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Frederick
 */
public class Message extends javax.swing.JPanel {

    private String popupType = "ERROR_MESSAGE";
    /**
     * Creates new form Message
     */
    public Message() {
        initComponents();
        setOpaque(false);
        txpnMessage.setBackground(new Color(0,0,0,0));
        txpnMessage.setSelectedTextColor(new Color(172,204,234));
        txpnMessage.setOpaque(false);
        popupType = "ERROR_MESSAGE";
        btnCancel.setPreferredSize(new Dimension(0, 0));
        txtTitle.setText("¡Ha ocurrido un error!");
    }
    
    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponents(grphcs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txpnMessage = new javax.swing.JTextPane();
        btnAcept = new ec.edu.espe.organivent.view.Button();
        btnCancel = new ec.edu.espe.organivent.view.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        setMaximumSize(new java.awt.Dimension(360, 210));
        setMinimumSize(new java.awt.Dimension(360, 210));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(360, 210));

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(48, 88, 149));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText(org.openide.util.NbBundle.getMessage(Message.class, "Message.txtTitle.text")); // NOI18N

        txpnMessage.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txpnMessage.setForeground(new java.awt.Color(102, 102, 102));
        txpnMessage.setText(org.openide.util.NbBundle.getMessage(Message.class, "Message.txpnMessage.text")); // NOI18N

        btnAcept.setBackground(new java.awt.Color(136, 186, 232));
        btnAcept.setForeground(new java.awt.Color(255, 255, 255));
        btnAcept.setText(org.openide.util.NbBundle.getMessage(Message.class, "Message.btnAcept.text")); // NOI18N
        btnAcept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptMouseClicked(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(136, 186, 232));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText(org.openide.util.NbBundle.getMessage(Message.class, "Message.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txpnMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txpnMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void eventAcept(ActionListener event){
        if("CONFIRMATION".equals(popupType)){
           btnAcept.addActionListener(event);
       }
    }
    
    private void btnAceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptMouseClicked
        if("ERROR_MESSAGE".equals(popupType)){
            GlassPanePopup.closePopupLast();
        }
    }//GEN-LAST:event_btnAceptMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       if("CONFIRMATION".equals(popupType)){
           GlassPanePopup.closePopupLast();
       }
    }//GEN-LAST:event_btnCancelActionPerformed

    public Message(String type){
        initComponents();
        setOpaque(false);
        txpnMessage.setBackground(new Color(0,0,0,0));
        txpnMessage.setSelectedTextColor(new Color(172,204,234));
        txpnMessage.setOpaque(false);
        if("CONFIRMATION".equals(type)){
            popupType = "CONFIRMATION";
            btnCancel.setPreferredSize(new Dimension(52, 30));
            txtTitle.setText("Seleccione una opción para continuar");
        }
    }
    
    
    public void setMessage(String Message){
        txpnMessage.setText(Message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ec.edu.espe.organivent.view.Button btnAcept;
    private ec.edu.espe.organivent.view.Button btnCancel;
    private javax.swing.JTextPane txpnMessage;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
