package ec.edu.espe.organivent.view;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Frederick
 */
public class PnlAddEquipment extends javax.swing.JPanel {

    private Color btnDefaultColor = new Color(63,115,193);
    private Color btnHoverColor = new Color(48,88,149);
    
    /**
     * Creates new form PnlAddEmployee
     */
    public PnlAddEquipment() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtCosto = new javax.swing.JLabel();
        txtIdValueEquipment = new javax.swing.JLabel();
        txtTipoEquipo = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JPanel();
        txtConfirmbtn = new javax.swing.JLabel();
        txtIdEquipment = new javax.swing.JLabel();
        SpnQuantity = new javax.swing.JSpinner();
        txdEquipmentType = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JLabel();
        FtdCost = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(390, 375));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setText("Añadir Equipo");
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtCosto.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtCosto.setForeground(new java.awt.Color(135, 132, 132));
        txtCosto.setText("Costo:");
        add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtIdValueEquipment.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtIdValueEquipment.setText("0");
        add(txtIdValueEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 98, 90, -1));

        txtTipoEquipo.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtTipoEquipo.setForeground(new java.awt.Color(135, 132, 132));
        txtTipoEquipo.setText("Tipo:");
        add(txtTipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btnConfirm.setBackground(new java.awt.Color(63, 115, 193));
        btnConfirm.setPreferredSize(new java.awt.Dimension(138, 31));

        txtConfirmbtn.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        txtConfirmbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConfirmbtn.setText("Confirmar");
        txtConfirmbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConfirmbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConfirmLayout = new javax.swing.GroupLayout(btnConfirm);
        btnConfirm.setLayout(btnConfirmLayout);
        btnConfirmLayout.setHorizontalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfirmLayout.createSequentialGroup()
                .addComponent(txtConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnConfirmLayout.setVerticalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConfirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        txtIdEquipment.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtIdEquipment.setForeground(new java.awt.Color(135, 132, 132));
        txtIdEquipment.setText("Id:");
        add(txtIdEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 98, -1, -1));

        SpnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(SpnQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 190, -1));

        txdEquipmentType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txdEquipmentTypeKeyTyped(evt);
            }
        });
        add(txdEquipmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 190, -1));

        txtCantidad.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(135, 132, 132));
        txtCantidad.setText("Cantidad:");
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        FtdCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        add(FtdCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseEntered
       btnConfirm.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtConfirmbtnMouseEntered

    private void txtConfirmbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseExited
        btnConfirm.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtConfirmbtnMouseExited

    private void txdEquipmentTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txdEquipmentTypeKeyTyped
            if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)){
        evt.consume();
    }
    }//GEN-LAST:event_txdEquipmentTypeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtdCost;
    private javax.swing.JSpinner SpnQuantity;
    private javax.swing.JPanel btnConfirm;
    private javax.swing.JTextField txdEquipmentType;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtConfirmbtn;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtIdEquipment;
    private javax.swing.JLabel txtIdValueEquipment;
    private javax.swing.JLabel txtTipoEquipo;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
