package ec.edu.espe.organivent.view;

import java.awt.Color;

/**
 *
 * @author Frederick Tipan, Gabriel Vivanco, Jefferson Yepez - Bit Coderz - DCCO ESPE
 */
public class PnlAddEvent1 extends javax.swing.JPanel {

    /**
     * Creates new form PnlAddEvent
     */
    public PnlAddEvent1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        txtTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtId = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JLabel();
        txtEndTime = new javax.swing.JLabel();
        txtArtist = new javax.swing.JLabel();
        txtEventplace = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnNextPage = new javax.swing.JPanel();
        txtNextPagebtn = new javax.swing.JLabel();
        dtcEndTime = new com.toedter.calendar.JDateChooser();
        dtcStartTime = new com.toedter.calendar.JDateChooser();
        cmbArtist = new javax.swing.JComboBox<>();
        cmbEventPlace = new javax.swing.JComboBox<>();
        spnStartTime = new javax.swing.JSpinner();
        spnEndTime = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(32, 108, 141));
        txtTitle.setText("Crear Evento");

        jSeparator1.setForeground(new java.awt.Color(116, 178, 237));

        txtId.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(135, 132, 132));
        txtId.setText("Id:");

        txtStartTime.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtStartTime.setForeground(new java.awt.Color(135, 132, 132));
        txtStartTime.setText("Fecha de inicio:");

        txtEndTime.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtEndTime.setForeground(new java.awt.Color(135, 132, 132));
        txtEndTime.setText("Fecha de Fin:");

        txtArtist.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtArtist.setForeground(new java.awt.Color(135, 132, 132));
        txtArtist.setText("Artista:");

        txtEventplace.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtEventplace.setForeground(new java.awt.Color(135, 132, 132));
        txtEventplace.setText("Lugar del evento:");

        jSeparator2.setForeground(new java.awt.Color(116, 178, 237));

        btnNextPage.setBackground(new java.awt.Color(63, 115, 193));
        btnNextPage.setPreferredSize(new java.awt.Dimension(142, 27));

        txtNextPagebtn.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        txtNextPagebtn.setForeground(new java.awt.Color(255, 255, 255));
        txtNextPagebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNextPagebtn.setText("Siguente");
        txtNextPagebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNextPagebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNextPagebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNextPagebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNextPagebtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNextPageLayout = new javax.swing.GroupLayout(btnNextPage);
        btnNextPage.setLayout(btnNextPageLayout);
        btnNextPageLayout.setHorizontalGroup(
            btnNextPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNextPagebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        btnNextPageLayout.setVerticalGroup(
            btnNextPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNextPagebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        dtcEndTime.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        dtcStartTime.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        cmbArtist.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        cmbArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEventPlace.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        cmbEventPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spnStartTime.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        spnStartTime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spnEndTime.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(txtTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtId)
                                    .addComponent(txtStartTime)
                                    .addComponent(txtEndTime)
                                    .addComponent(txtArtist))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtcStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(dtcEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbArtist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEventplace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEventPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStartTime)
                    .addComponent(dtcStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndTime)
                            .addComponent(spnEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArtist)
                            .addComponent(cmbArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dtcEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEventplace)
                    .addComponent(cmbEventPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNextPagebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNextPagebtnMouseClicked
       
    }//GEN-LAST:event_txtNextPagebtnMouseClicked

    private void txtNextPagebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNextPagebtnMouseEntered
        btnNextPage.setBackground(new Color(48,88,149));
    }//GEN-LAST:event_txtNextPagebtnMouseEntered

    private void txtNextPagebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNextPagebtnMouseExited
        btnNextPage.setBackground(new Color(63,115,193));
    }//GEN-LAST:event_txtNextPagebtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnNextPage;
    private javax.swing.JComboBox<String> cmbArtist;
    private javax.swing.JComboBox<String> cmbEventPlace;
    private com.toedter.calendar.JDateChooser dtcEndTime;
    private com.toedter.calendar.JDateChooser dtcStartTime;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner spnEndTime;
    private javax.swing.JSpinner spnStartTime;
    private javax.swing.JLabel txtArtist;
    private javax.swing.JLabel txtEndTime;
    private javax.swing.JLabel txtEventplace;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtNextPagebtn;
    private javax.swing.JLabel txtStartTime;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
