package ec.edu.espe.organivent.view;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Frederick
 */
public class PnlAddEventPlace extends javax.swing.JPanel {

    private Color btnDefaultColor = new Color(63,115,193);
    private Color btnHoverColor = new Color(48,88,149);
    
    /**
     * Creates new form PnlAddEmployee
     */
    public PnlAddEventPlace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtAdress = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JPanel();
        txtConfirmbtn = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JLabel();
        txtRentCost = new javax.swing.JLabel();
        txtEventPlaceName = new javax.swing.JTextField();
        tfdAdress = new javax.swing.JTextField();
        txdRentCost = new javax.swing.JTextField();
        sldCapacity = new javax.swing.JSlider();
        etiValor = new javax.swing.JLabel();
        etiCapacidad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(390, 375));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setText("Añadir Lugar");
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        txtAdress.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtAdress.setForeground(new java.awt.Color(135, 132, 132));
        txtAdress.setText("Dirección:");
        add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        btnConfirm.setBackground(new java.awt.Color(63, 115, 193));
        btnConfirm.setPreferredSize(new java.awt.Dimension(138, 31));

        txtConfirmbtn.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        txtConfirmbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConfirmbtn.setText("Confirmar");
        txtConfirmbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConfirmbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConfirmLayout = new javax.swing.GroupLayout(btnConfirm);
        btnConfirm.setLayout(btnConfirmLayout);
        btnConfirmLayout.setHorizontalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConfirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnConfirmLayout.setVerticalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConfirmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        txtName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(135, 132, 132));
        txtName.setText("Nombre del sitio:");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 20));

        txtCapacity.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtCapacity.setForeground(new java.awt.Color(135, 132, 132));
        txtCapacity.setText("Capacidad:");
        add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtRentCost.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtRentCost.setForeground(new java.awt.Color(135, 132, 132));
        txtRentCost.setText("Costo de renta:");
        add(txtRentCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtEventPlaceName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEventPlaceNameKeyTyped(evt);
            }
        });
        add(txtEventPlaceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, -1));

        tfdAdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdAdressKeyTyped(evt);
            }
        });
        add(tfdAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 210, -1));
        add(txdRentCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 210, -1));

        sldCapacity.setMajorTickSpacing(10000);
        sldCapacity.setMaximum(30000);
        sldCapacity.setMinorTickSpacing(1000);
        sldCapacity.setPaintLabels(true);
        sldCapacity.setPaintTicks(true);
        sldCapacity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldCapacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldCapacityStateChanged(evt);
            }
        });
        add(sldCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, 40));
        add(etiValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 80, -1));

        etiCapacidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(etiCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseEntered
       btnConfirm.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtConfirmbtnMouseEntered

    private void txtConfirmbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseExited
        btnConfirm.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtConfirmbtnMouseExited

    private void sldCapacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldCapacityStateChanged
        // TODO add your handling code here:
        etiCapacidad.setText(sldCapacity.getValue()+" personas");
    }//GEN-LAST:event_sldCapacityStateChanged

    private void txtEventPlaceNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEventPlaceNameKeyTyped
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtEventPlaceNameKeyTyped

    private void tfdAdressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdAdressKeyTyped
        char keyChar = evt.getKeyChar();
    
        if (!(Character.isLetterOrDigit(keyChar) || Character.isWhitespace(keyChar))) {
            evt.consume();
        }
    }//GEN-LAST:event_tfdAdressKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnConfirm;
    private javax.swing.JLabel etiCapacidad;
    private javax.swing.JLabel etiValor;
    private javax.swing.JSlider sldCapacity;
    private javax.swing.JTextField tfdAdress;
    private javax.swing.JTextField txdRentCost;
    private javax.swing.JLabel txtAdress;
    private javax.swing.JLabel txtCapacity;
    private javax.swing.JLabel txtConfirmbtn;
    private javax.swing.JTextField txtEventPlaceName;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtRentCost;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
