package ec.edu.espe.organivent.view;

import ec.edu.espe.organivent.controller.EquipmentController;
import ec.edu.espe.organivent.controller.StaffController;
import ec.edu.espe.organivent.model.Equipment;
import ec.edu.espe.organivent.model.Staff;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Frederick Tipan, Gabriel Vivanco, Jefferson Yepez - Bit Coderz - DCCO ESPE
 */
public class PnlAddEvent2 extends javax.swing.JPanel {
    private Color btnDefaultColor = new Color(63,115,193);
    private Color btnHoverColor = new Color(48,88,149);

    /**
     * Creates new form PnlAddEvent
     */
    public PnlAddEvent2() {
        initComponents();
        loadStaff();
        loadEquipment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        txtConfirmbtn3 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        txtStaff = new javax.swing.JLabel();
        txtEquipamiento = new javax.swing.JLabel();
        btnReturn = new javax.swing.JPanel();
        txtReturnbtn = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JPanel();
        txtConfirmbtn = new javax.swing.JLabel();
        btnPenaltyFees = new javax.swing.JPanel();
        txtPenaltyFeeBtn = new javax.swing.JLabel();
        btnGeneralExpenses = new javax.swing.JPanel();
        txtGeneralExpensesBtn = new javax.swing.JLabel();
        scpnStaff = new javax.swing.JScrollPane();
        lstStaff = new javax.swing.JList<>();
        scpnEquipment = new javax.swing.JScrollPane();
        lstEquipment = new javax.swing.JList<>();

        txtConfirmbtn3.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        txtConfirmbtn3.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmbtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConfirmbtn3.setText("Regresar");
        txtConfirmbtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConfirmbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConfirmbtn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtConfirmbtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtConfirmbtn3MouseExited(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(32, 108, 141));
        txtTitle.setText("Crear Evento");
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 14, -1, -1));

        txtStaff.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtStaff.setForeground(new java.awt.Color(135, 132, 132));
        txtStaff.setText("Staff:");
        add(txtStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        txtEquipamiento.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtEquipamiento.setForeground(new java.awt.Color(135, 132, 132));
        txtEquipamiento.setText("Equipamiento:");
        add(txtEquipamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnReturn.setBackground(new java.awt.Color(63, 115, 193));
        btnReturn.setToolTipText("");
        btnReturn.setPreferredSize(new java.awt.Dimension(142, 27));

        txtReturnbtn.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtReturnbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtReturnbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReturnbtn.setText("Regresar");
        txtReturnbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReturnLayout = new javax.swing.GroupLayout(btnReturn);
        btnReturn.setLayout(btnReturnLayout);
        btnReturnLayout.setHorizontalGroup(
            btnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtReturnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        btnReturnLayout.setVerticalGroup(
            btnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtReturnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 358, -1, -1));

        btnConfirm.setBackground(new java.awt.Color(63, 115, 193));
        btnConfirm.setPreferredSize(new java.awt.Dimension(142, 27));

        txtConfirmbtn.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtConfirmbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConfirmbtn.setText("Confirmar");
        txtConfirmbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnConfirmLayout = new javax.swing.GroupLayout(btnConfirm);
        btnConfirm.setLayout(btnConfirmLayout);
        btnConfirmLayout.setHorizontalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtConfirmbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        btnConfirmLayout.setVerticalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtConfirmbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 358, -1, -1));

        btnPenaltyFees.setBackground(new java.awt.Color(63, 194, 193));
        btnPenaltyFees.setPreferredSize(new java.awt.Dimension(142, 27));

        txtPenaltyFeeBtn.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtPenaltyFeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        txtPenaltyFeeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPenaltyFeeBtn.setText("Agregar Multas");
        txtPenaltyFeeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnPenaltyFeesLayout = new javax.swing.GroupLayout(btnPenaltyFees);
        btnPenaltyFees.setLayout(btnPenaltyFeesLayout);
        btnPenaltyFeesLayout.setHorizontalGroup(
            btnPenaltyFeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPenaltyFeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        btnPenaltyFeesLayout.setVerticalGroup(
            btnPenaltyFeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPenaltyFeeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        add(btnPenaltyFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 284, 263, 39));

        btnGeneralExpenses.setBackground(new java.awt.Color(63, 194, 193));
        btnGeneralExpenses.setPreferredSize(new java.awt.Dimension(142, 27));

        txtGeneralExpensesBtn.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtGeneralExpensesBtn.setForeground(new java.awt.Color(255, 255, 255));
        txtGeneralExpensesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGeneralExpensesBtn.setText("Agregar Gastos Generales");
        txtGeneralExpensesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnGeneralExpensesLayout = new javax.swing.GroupLayout(btnGeneralExpenses);
        btnGeneralExpenses.setLayout(btnGeneralExpensesLayout);
        btnGeneralExpensesLayout.setHorizontalGroup(
            btnGeneralExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGeneralExpensesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        btnGeneralExpensesLayout.setVerticalGroup(
            btnGeneralExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGeneralExpensesBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        add(btnGeneralExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 227, 263, 39));

        lstStaff.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scpnStaff.setViewportView(lstStaff);

        add(scpnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, 60));

        lstEquipment.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scpnEquipment.setViewportView(lstEquipment);

        add(scpnEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmbtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmbtn3MouseExited

    private void txtConfirmbtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmbtn3MouseEntered

    private void txtConfirmbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmbtn3MouseClicked

    private void loadStaff(){
        DefaultListModel listModel = new DefaultListModel();
        StaffController stfc = new StaffController();
        
        ArrayList<Staff> availableStaff = stfc.read();
        
        String display;
        
        for(Staff currentStaff:availableStaff){
            display = currentStaff.getId() + " " + currentStaff.getType();
            listModel.addElement(display);
        }
        
        lstStaff.setModel(listModel);
    }
    
    private void loadEquipment(){
        DefaultListModel listModel = new DefaultListModel();
        EquipmentController eqmc = new EquipmentController();
        
        ArrayList<Equipment> availableEquip = eqmc.read();
        
        for(Equipment currentEquip:availableEquip){
            listModel.addElement(currentEquip.getType());
        }
        
        lstStaff.setModel(listModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnConfirm;
    private javax.swing.JPanel btnGeneralExpenses;
    private javax.swing.JPanel btnPenaltyFees;
    private javax.swing.JPanel btnReturn;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JList<String> lstEquipment;
    private javax.swing.JList<String> lstStaff;
    private javax.swing.JScrollPane scpnEquipment;
    private javax.swing.JScrollPane scpnStaff;
    private javax.swing.JLabel txtConfirmbtn;
    private javax.swing.JLabel txtConfirmbtn3;
    private javax.swing.JLabel txtEquipamiento;
    private javax.swing.JLabel txtGeneralExpensesBtn;
    private javax.swing.JLabel txtPenaltyFeeBtn;
    private javax.swing.JLabel txtReturnbtn;
    private javax.swing.JLabel txtStaff;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
