package ec.edu.espe.organivent.view;

import ec.edu.espe.organivent.controller.ArtistController;
import ec.edu.espe.organivent.model.Artist;
import ec.edu.espe.organivent.utils.HandleInput;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Frederick
 */
public class PnlAddArtist extends javax.swing.JPanel {

    private Color btnDefaultColor = new Color(63,115,193);
    private Color btnHoverColor = new Color(48,88,149);
    private Artist artist;
    
    /**
     * Creates new form PnlAddEmployee
     */
    public PnlAddArtist() {
        initComponents();
        asignNewId();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtSalario = new javax.swing.JLabel();
        txtIdValue = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JPanel();
        txtConfirmbtn = new javax.swing.JLabel();
        txtId1 = new javax.swing.JLabel();
        tfdName = new javax.swing.JTextField();
        fdlWage = new javax.swing.JFormattedTextField();
        sptNombre = new javax.swing.JSeparator();
        sptSalario = new javax.swing.JSeparator();
        btnReadArtist = new javax.swing.JPanel();
        txtReadArtistBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(390, 375));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        txtTitle.setText("Añadir Artista");
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtSalario.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtSalario.setForeground(new java.awt.Color(135, 132, 132));
        txtSalario.setText("Salario:   $");
        add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 192, -1, -1));

        txtIdValue.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtIdValue.setText("0");
        add(txtIdValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 98, 90, -1));

        txtNombre.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(135, 132, 132));
        txtNombre.setText("Nombre:");
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        btnConfirm.setBackground(new java.awt.Color(63, 115, 193));
        btnConfirm.setPreferredSize(new java.awt.Dimension(138, 31));

        txtConfirmbtn.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        txtConfirmbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConfirmbtn.setText("Confirmar");
        txtConfirmbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConfirmbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtConfirmbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConfirmLayout = new javax.swing.GroupLayout(btnConfirm);
        btnConfirm.setLayout(btnConfirmLayout);
        btnConfirmLayout.setHorizontalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfirmLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtConfirmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        btnConfirmLayout.setVerticalGroup(
            btnConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtConfirmbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        txtId1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtId1.setForeground(new java.awt.Color(135, 132, 132));
        txtId1.setText("Id:");
        add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 98, -1, -1));

        tfdName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfdName.setBorder(null);
        tfdName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdNameKeyTyped(evt);
            }
        });
        add(tfdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 141, 200, -1));

        fdlWage.setBorder(null);
        fdlWage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        fdlWage.setText("0,00");
        add(fdlWage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 192, 170, -1));

        sptNombre.setBackground(new java.awt.Color(116, 178, 237));
        sptNombre.setForeground(new java.awt.Color(116, 178, 237));
        sptNombre.setOpaque(true);
        sptNombre.setPreferredSize(new java.awt.Dimension(197, 1));
        add(sptNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 162, -1, -1));

        sptSalario.setBackground(new java.awt.Color(116, 178, 237));
        sptSalario.setForeground(new java.awt.Color(116, 178, 237));
        sptSalario.setOpaque(true);
        sptSalario.setPreferredSize(new java.awt.Dimension(197, 1));
        add(sptSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 214, -1, -1));

        btnReadArtist.setBackground(new java.awt.Color(63, 115, 193));
        btnReadArtist.setPreferredSize(new java.awt.Dimension(138, 31));

        txtReadArtistBtn.setFont(new java.awt.Font("Inter SemiBold", 0, 15)); // NOI18N
        txtReadArtistBtn.setForeground(new java.awt.Color(255, 255, 255));
        txtReadArtistBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReadArtistBtn.setText("Visualizar artistas");
        txtReadArtistBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtReadArtistBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReadArtistBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReadArtistBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReadArtistBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnReadArtistLayout = new javax.swing.GroupLayout(btnReadArtist);
        btnReadArtist.setLayout(btnReadArtistLayout);
        btnReadArtistLayout.setHorizontalGroup(
            btnReadArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtReadArtistBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        btnReadArtistLayout.setVerticalGroup(
            btnReadArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtReadArtistBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        add(btnReadArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseEntered
       btnConfirm.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtConfirmbtnMouseEntered

    private void txtConfirmbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseExited
        btnConfirm.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtConfirmbtnMouseExited

    private void tfdNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdNameKeyTyped
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)){
        evt.consume();
    }
    }//GEN-LAST:event_tfdNameKeyTyped

    private void txtConfirmbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmbtnMouseClicked
       boolean canContinue = validateData();

        if(canContinue==true){
            sendArtistData();
        } 
    }//GEN-LAST:event_txtConfirmbtnMouseClicked

    private void txtReadArtistBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReadArtistBtnMouseClicked
        FrmReadArtist frmReadArtist = new FrmReadArtist();
        frmReadArtist.setVisible(true);
    }//GEN-LAST:event_txtReadArtistBtnMouseClicked

    private void txtReadArtistBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReadArtistBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReadArtistBtnMouseEntered

    private void txtReadArtistBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReadArtistBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReadArtistBtnMouseExited

    private boolean validateData(){
        boolean passed = true;
        
        passed = HandleInput.validateRealName(tfdName.getText());
        if(passed){
            passed = HandleInput.validatePriceString(fdlWage.getText());
        }
        return passed;
    }
    
    private void sendArtistData(){
        int asignedId = Integer.parseInt(txtIdValue.getText());
        String insertedName = tfdName.getText();
        float insertedWage = HandleInput.returnFloat(fdlWage.getText());
        
        artist = new Artist(asignedId, insertedName, insertedWage);
        
        ArtistController artistc = new ArtistController();
        artistc.create(artist);
        
        emptyFields();
        asignNewId();
    }
    
    private void emptyFields(){
        tfdName.setText("");
        fdlWage.setText("0,00");
    }
    
    private void asignNewId(){
        ArtistController artistc = new ArtistController();
        int asignedId = artistc.asignNewId();
        String displayNewId = Integer.toString(asignedId);
        
        txtIdValue.setText(displayNewId);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnConfirm;
    private javax.swing.JPanel btnReadArtist;
    private javax.swing.JFormattedTextField fdlWage;
    private javax.swing.JSeparator sptNombre;
    private javax.swing.JSeparator sptSalario;
    private javax.swing.JTextField tfdName;
    private javax.swing.JLabel txtConfirmbtn;
    private javax.swing.JLabel txtId1;
    private javax.swing.JLabel txtIdValue;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtReadArtistBtn;
    private javax.swing.JLabel txtSalario;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
