package ec.edu.espe.organivent.view;

import java.awt.Color;

/**
 *
 * @author Frederick
 */
public class PnlEventMainMenu extends javax.swing.JPanel {

    private Color btnDefaultColor = new Color(63,115,193);
    private Color btnHoverColor = new Color(48,88,149);
    private FrmReadEvent showEvents;
    
    
    /**
     * Creates new form PnladdEventFormat
     */
    public PnlEventMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        btnDeleteBill = new javax.swing.JPanel();
        txtDeleteBillbtn = new javax.swing.JLabel();
        btnSeeBill = new javax.swing.JPanel();
        txtSeeBillbtn = new javax.swing.JLabel();
        btnAddEvent = new javax.swing.JPanel();
        txtAddEventbtn = new javax.swing.JLabel();
        btnCalculateEventCost = new javax.swing.JPanel();
        txtCalcEvnCstbtn = new javax.swing.JLabel();
        btnSeeEvent = new javax.swing.JPanel();
        txtSeeEvent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(390, 375));
        setMinimumSize(new java.awt.Dimension(390, 375));
        setPreferredSize(new java.awt.Dimension(390, 375));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(172, 204, 234));

        title1.setBackground(new java.awt.Color(32, 108, 141));
        title1.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        title1.setForeground(new java.awt.Color(32, 108, 141));
        title1.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.title1.text")); // NOI18N

        title2.setFont(new java.awt.Font("Inter SemiBold", 0, 20)); // NOI18N
        title2.setForeground(new java.awt.Color(32, 108, 141));
        title2.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.title2.text")); // NOI18N

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(title1))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(title2)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 90));

        btnDeleteBill.setBackground(new java.awt.Color(63, 115, 193));
        btnDeleteBill.setMaximumSize(new java.awt.Dimension(142, 47));
        btnDeleteBill.setMinimumSize(new java.awt.Dimension(142, 47));

        txtDeleteBillbtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtDeleteBillbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtDeleteBillbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDeleteBillbtn.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.txtDeleteBillbtn.text")); // NOI18N
        txtDeleteBillbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDeleteBillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDeleteBillbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDeleteBillbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDeleteBillbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDeleteBillLayout = new javax.swing.GroupLayout(btnDeleteBill);
        btnDeleteBill.setLayout(btnDeleteBillLayout);
        btnDeleteBillLayout.setHorizontalGroup(
            btnDeleteBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDeleteBillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        btnDeleteBillLayout.setVerticalGroup(
            btnDeleteBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDeleteBillLayout.createSequentialGroup()
                .addComponent(txtDeleteBillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(btnDeleteBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 270, 30));

        btnSeeBill.setBackground(new java.awt.Color(63, 115, 193));
        btnSeeBill.setMaximumSize(new java.awt.Dimension(142, 47));
        btnSeeBill.setMinimumSize(new java.awt.Dimension(142, 47));

        txtSeeBillbtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtSeeBillbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtSeeBillbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSeeBillbtn.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.txtSeeBillbtn.text")); // NOI18N
        txtSeeBillbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSeeBillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSeeBillbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSeeBillbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSeeBillbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSeeBillLayout = new javax.swing.GroupLayout(btnSeeBill);
        btnSeeBill.setLayout(btnSeeBillLayout);
        btnSeeBillLayout.setHorizontalGroup(
            btnSeeBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSeeBillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        btnSeeBillLayout.setVerticalGroup(
            btnSeeBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSeeBillLayout.createSequentialGroup()
                .addComponent(txtSeeBillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(btnSeeBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 265, 270, 30));

        btnAddEvent.setBackground(new java.awt.Color(63, 115, 193));
        btnAddEvent.setMaximumSize(new java.awt.Dimension(142, 47));
        btnAddEvent.setMinimumSize(new java.awt.Dimension(142, 47));

        txtAddEventbtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtAddEventbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtAddEventbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddEventbtn.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.txtAddEventbtn.text")); // NOI18N
        txtAddEventbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAddEventbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddEventbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAddEventbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAddEventbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddEventLayout = new javax.swing.GroupLayout(btnAddEvent);
        btnAddEvent.setLayout(btnAddEventLayout);
        btnAddEventLayout.setHorizontalGroup(
            btnAddEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAddEventbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        btnAddEventLayout.setVerticalGroup(
            btnAddEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddEventLayout.createSequentialGroup()
                .addComponent(txtAddEventbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        add(btnAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 165, 270, 30));

        btnCalculateEventCost.setBackground(new java.awt.Color(63, 115, 193));
        btnCalculateEventCost.setMaximumSize(new java.awt.Dimension(142, 47));
        btnCalculateEventCost.setMinimumSize(new java.awt.Dimension(142, 47));

        txtCalcEvnCstbtn.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtCalcEvnCstbtn.setForeground(new java.awt.Color(255, 255, 255));
        txtCalcEvnCstbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCalcEvnCstbtn.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.txtCalcEvnCstbtn.text")); // NOI18N
        txtCalcEvnCstbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCalcEvnCstbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCalcEvnCstbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCalcEvnCstbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCalcEvnCstbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCalculateEventCostLayout = new javax.swing.GroupLayout(btnCalculateEventCost);
        btnCalculateEventCost.setLayout(btnCalculateEventCostLayout);
        btnCalculateEventCostLayout.setHorizontalGroup(
            btnCalculateEventCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCalcEvnCstbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        btnCalculateEventCostLayout.setVerticalGroup(
            btnCalculateEventCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCalculateEventCostLayout.createSequentialGroup()
                .addComponent(txtCalcEvnCstbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        add(btnCalculateEventCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 215, 270, 30));

        btnSeeEvent.setBackground(new java.awt.Color(63, 115, 193));
        btnSeeEvent.setMaximumSize(new java.awt.Dimension(142, 47));
        btnSeeEvent.setMinimumSize(new java.awt.Dimension(142, 47));
        btnSeeEvent.setPreferredSize(new java.awt.Dimension(142, 47));

        txtSeeEvent.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtSeeEvent.setForeground(new java.awt.Color(255, 255, 255));
        txtSeeEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSeeEvent.setText(org.openide.util.NbBundle.getMessage(PnlEventMainMenu.class, "PnlEventMainMenu.txtSeeEvent.text")); // NOI18N
        txtSeeEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSeeEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSeeEventMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSeeEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSeeEventMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSeeEventLayout = new javax.swing.GroupLayout(btnSeeEvent);
        btnSeeEvent.setLayout(btnSeeEventLayout);
        btnSeeEventLayout.setHorizontalGroup(
            btnSeeEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSeeEventLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSeeEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSeeEventLayout.setVerticalGroup(
            btnSeeEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSeeEventLayout.createSequentialGroup()
                .addComponent(txtSeeEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        add(btnSeeEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 115, 270, 30));
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtSeeEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeeEventMouseEntered
        btnSeeEvent.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtSeeEventMouseEntered

    private void txtSeeEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeeEventMouseExited
        btnSeeEvent.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtSeeEventMouseExited

    private void txtAddEventbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddEventbtnMouseEntered
        btnAddEvent.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtAddEventbtnMouseEntered

    private void txtAddEventbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddEventbtnMouseExited
        btnAddEvent.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtAddEventbtnMouseExited

    private void txtCalcEvnCstbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalcEvnCstbtnMouseEntered
        btnCalculateEventCost.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtCalcEvnCstbtnMouseEntered

    private void txtCalcEvnCstbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalcEvnCstbtnMouseExited
        btnCalculateEventCost.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtCalcEvnCstbtnMouseExited

    private void txtSeeBillbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeeBillbtnMouseEntered
        btnSeeBill.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtSeeBillbtnMouseEntered

    private void txtSeeBillbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeeBillbtnMouseExited
        btnSeeBill.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtSeeBillbtnMouseExited

    private void txtDeleteBillbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteBillbtnMouseEntered
        btnDeleteBill.setBackground(btnHoverColor);
    }//GEN-LAST:event_txtDeleteBillbtnMouseEntered

    private void txtDeleteBillbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteBillbtnMouseExited
        btnDeleteBill.setBackground(btnDefaultColor);
    }//GEN-LAST:event_txtDeleteBillbtnMouseExited

    private void txtSeeEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeeEventMouseClicked
        FrmReadEvent showEvent = new FrmReadEvent();
        showEvent.setVisible(true);
    }//GEN-LAST:event_txtSeeEventMouseClicked

    private void txtAddEventbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddEventbtnMouseClicked
        FrmAddEvent addEventGUI = new FrmAddEvent();
        addEventGUI.setVisible(true);
    }//GEN-LAST:event_txtAddEventbtnMouseClicked

    private void txtCalcEvnCstbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalcEvnCstbtnMouseClicked
        FrmCalculateTotalCostEvent calcTotalGUI = new FrmCalculateTotalCostEvent();
        calcTotalGUI.setVisible(true);
    }//GEN-LAST:event_txtCalcEvnCstbtnMouseClicked

    private void txtSeeBillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSeeBillbtnMouseClicked
        FrmReadBill readBillGUI = new FrmReadBill();
        readBillGUI.setVisible(true);
    }//GEN-LAST:event_txtSeeBillbtnMouseClicked

    private void txtDeleteBillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteBillbtnMouseClicked
        FrmDeleteBill deletedBillGUI = new FrmDeleteBill();
        deletedBillGUI.setVisible(true);
    }//GEN-LAST:event_txtDeleteBillbtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddEvent;
    private javax.swing.JPanel btnCalculateEventCost;
    private javax.swing.JPanel btnDeleteBill;
    private javax.swing.JPanel btnSeeBill;
    private javax.swing.JPanel btnSeeEvent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel txtAddEventbtn;
    private javax.swing.JLabel txtCalcEvnCstbtn;
    private javax.swing.JLabel txtDeleteBillbtn;
    private javax.swing.JLabel txtSeeBillbtn;
    private javax.swing.JLabel txtSeeEvent;
    // End of variables declaration//GEN-END:variables
}
